sonar.projectKey=directorio-activo-ingest
sonar.projectName=Directorio Activo Ingest
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/build/**,**/.terraform/**
sonar.coverage.exclusions=tests/**
